"""Surface-finish (roughness) specifications for the drawing.

**Read this before trusting a roughness value.**

Unlike every other annotation AutoDraft draws, these are *not* measured from
the model and *not* read from the file. No sample model carries finish data:
all 18 STEP files were searched for ``SURFACE_TEXTURE``, surface-condition
and roughness entities and contain none, and a B-rep has no notion of finish
at all -- it is a manufacturing requirement a designer states, not a property
of the geometry.

They are therefore **assigned deterministically from a hash of the part
name**, so that the detector has positive examples of the ``roughnesses``
class to learn from. The values are drawn from finishes that are real and
standard (the ISO 1302 / ASME B46.1 preferred Ra series) and are attached to
plausible targets (a general note for the part, a leader on a bore wall), so
the *symbol* and its formatting are exactly what a real drawing carries.

The consequences, stated plainly:

* The **class, symbol, placement and text formatting are realistic** and are
  what the detector should learn.
* The **specific Ra value is synthetic**. It is reproducible for a given part
  name but carries no information about the real part. Do not train a
  regression from drawing -> Ra on this and expect it to mean anything, and
  do not quote from it.
* Every roughness annotation is flagged ``synthetic: true`` in the COCO
  ``attributes`` and in the JSON records, so this is machine-detectable
  downstream and can be filtered out.

Determinism is by BLAKE2b of the part name, not Python's ``hash()``, which is
salted per process and would give a different drawing on every run.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import List, Optional, Tuple

#: ISO 1302 preferred Ra values in micrometres. These are the roughnesses a
#: drawing actually specifies; arbitrary values like "Ra 2.7" do not occur.
PREFERRED_RA = (0.4, 0.8, 1.6, 3.2, 6.3, 12.5)

#: Which finishes are plausible for which target, so a bore does not get a
#: mirror finish and a general note does not demand lapping of every face.
_GENERAL_RA = (1.6, 3.2, 6.3, 12.5)
_BORE_RA = (0.4, 0.8, 1.6, 3.2)


@dataclass
class Roughness:
    """One surface-finish specification.

    ``ra`` is in micrometres, which is the unit ISO 1302 states Ra in -- this
    is the one place a value on an AutoDraft drawing is not in millimetres,
    because "Ra 0.0016" is not something any drawing prints.
    """

    ra: float
    general: bool = False       # True: applies to the whole part
    machined: bool = True       # material removal required (the barred symbol)
    target: Optional[Tuple[float, float, float]] = None   # model-space anchor
    synthetic: bool = True      # never measured; see the module docstring

    def text(self) -> str:
        """The text beside the symbol, e.g. ``Ra 1.6``."""
        v = f"{self.ra:g}"
        return f"Ra {v}"


def _rng(seed_text: str) -> int:
    """A stable integer from a name. BLAKE2b, because hash() is salted."""
    d = hashlib.blake2b(seed_text.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(d, "big")


def assign(part_name: str, info) -> List[Roughness]:
    """Pick this part's finish specifications, deterministically.

    Always yields one general note. A part with recognised closed bores also
    gets one bore finish, because a bored surface is the usual reason a
    drawing carries a second, tighter specification.

    The same ``part_name`` always yields the same result, so a drawing is
    reproducible and a dataset can be regenerated byte-for-byte.
    """
    seed = _rng(part_name)
    out = [Roughness(ra=_GENERAL_RA[seed % len(_GENERAL_RA)], general=True)]

    bores = [h for h in getattr(info, "holes", [])
             if getattr(h, "is_closed", True)]
    if bores:
        # Largest bore: the one a reader can actually see a leader pointing at.
        h = max(bores, key=lambda b: b.diameter)
        ra = _BORE_RA[(seed >> 8) % len(_BORE_RA)]
        out.append(Roughness(ra=ra, general=False,
                             target=(h.x, h.y, h.z)))
    return out
