"""Synthetic PMI: GD&T, threads and chamfers generated from real geometry.

**Read this before trusting any value produced here.**

Why this exists
---------------

Only one of the 18 sample models (the NIST AP242 part) carries any PMI at
all. Measured on the real dataset, that left three classes unusable:

    gdnts     9 objects, all on 1 image of 18   -- 0 in valid, 0 in test
    chamfers  1 object,  on 1 image             -- 0 in valid, 0 in test
    threads   1 object,  on 1 image             -- 0 in valid, 0 in test

A class with no instances in the validation and test splits cannot be
learned and cannot be evaluated, so the label set was seven classes in name
and four in practice. This module generates additional instances so every
class appears in every split.

What is and is not invented
---------------------------

The **geometry is always real**. Nothing here places a callout on a feature
that does not exist:

* a thread only ever goes on a genuine closed cylindrical bore, and only when
  that bore's diameter is close to a standard metric tap drill;
* a chamfer only goes on a genuine bore mouth, sized from that bore;
* flatness/parallelism only go on a genuine planar face of a plate;
* position only goes on a genuine hole or hole pattern;
* perpendicularity/cylindricity only go on a genuine bore.

The **specification is invented**. The tolerance magnitude, the thread pitch
class, the chamfer angle and the datum letters are chosen deterministically
from a hash of the part name. They are drawn from values that are real and
standard -- ISO 965 coarse-pitch metric threads, the ASME Y14.5 characteristic
set, tolerance magnitudes on the R10 preferred-number series, 45 deg and 30
deg chamfers -- and they are internally consistent: a position tolerance is
never tighter than the size tolerance of the hole it locates, a datum letter
is never referenced before it is defined, and a tapped hole's minor diameter
matches its stated nominal.

So a reader sees a plausible, self-consistent drawing, and a detector learns
a realistic distribution of marks. But **the numbers do not describe the real
part** and must not be quoted or used as regression targets.

Every generated item sets ``synthetic=True``, which reaches the COCO
``attributes.detail.synthetic`` field, so all of it is machine-detectable and
can be filtered or down-weighted downstream.

Determinism
-----------

Seeded by BLAKE2b of the part name, never Python's ``hash()`` (salted per
process). The same part always yields the same drawing, so a dataset can be
regenerated byte-for-byte and a train/valid/test split stays stable.
"""
from __future__ import annotations

import hashlib
from typing import List, Optional, Tuple

from .geometry import Chamfer
from .pmi import DatumFeature, GeomTolerance, PMI, Thread

# --------------------------------------------------------------------------- #
# standards data -- these are real, and are the whole point of "keep it real"
# --------------------------------------------------------------------------- #

#: ISO 965 COARSE pitch series: nominal diameter -> pitch, in mm. A tapped
#: hole is modelled at its tap-drill (minor) diameter, which is
#: nominal - pitch, so this table is also what maps a bore back to a thread.
#: Coarse is the default a drawing means when it does not say otherwise.
ISO_COARSE_PITCH = {
    1.0: 0.25, 1.2: 0.25, 1.6: 0.35, 2.0: 0.4, 2.5: 0.45, 3.0: 0.5,
    3.5: 0.6, 4.0: 0.7, 5.0: 0.8, 6.0: 1.0, 7.0: 1.0, 8.0: 1.25,
    10.0: 1.5, 12.0: 1.75, 14.0: 2.0, 16.0: 2.0, 18.0: 2.5, 20.0: 2.5,
    22.0: 2.5, 24.0: 3.0, 27.0: 3.0, 30.0: 3.5, 33.0: 3.5, 36.0: 4.0,
    39.0: 4.0, 42.0: 4.5, 45.0: 4.5, 48.0: 5.0,
}

#: ISO 965 FINE pitch series, as (nominal, pitch) pairs -- a nominal can have
#: several fine pitches (M10 x 1.25 and M10 x 1), so this cannot be a dict.
#: Fine threads are real and common on thin walls and adjusting features.
#:
#: The coarse table alone held 17 sizes and covered only ~40% of the 1-50 mm
#: diameter range, so most bores fell in a gap and were rejected as "not a
#: standard tap drill" when in fact a standard thread existed for them --
#: a 9.0 mm bore is an M10 x 1.25 tap drill, and a 3.5 mm bore an M4 x 0.5.
ISO_FINE_PITCH = (
    (2.0, 0.25), (2.5, 0.35), (3.0, 0.35), (4.0, 0.5), (5.0, 0.5),
    (6.0, 0.75), (8.0, 1.0), (8.0, 0.75), (10.0, 1.25), (10.0, 1.0),
    (10.0, 0.75), (12.0, 1.5), (12.0, 1.25), (12.0, 1.0), (14.0, 1.5),
    (16.0, 1.5), (18.0, 2.0), (18.0, 1.5), (20.0, 2.0), (20.0, 1.5),
    (22.0, 2.0), (22.0, 1.5), (24.0, 2.0), (27.0, 2.0), (30.0, 2.0),
    (33.0, 2.0), (36.0, 3.0), (36.0, 2.0), (39.0, 3.0), (42.0, 3.0),
    (45.0, 3.0), (48.0, 3.0),
)


def _thread_candidates():
    """All standard (tap_drill, nominal, pitch, coarse?) triples, once each."""
    out = [(round(n - p, 4), n, p, True) for n, p in ISO_COARSE_PITCH.items()]
    out += [(round(n - p, 4), n, p, False) for n, p in ISO_FINE_PITCH]
    return out

#: Tolerance classes that actually appear on drawings, medium fit first.
THREAD_CLASSES = ("6H", "6g", "6H/6g")

#: Above this diameter a bore that passes clean THROUGH the part reads as its
#: main aperture rather than a fastener hole -- flange.step's 45 mm centre and
#: bracket_plate's 40 mm cutout are the parts' openings, and calling them M48
#: or M45 is something no reader would accept.
#:
#: A BLIND bore of the same size is a different feature: it is a pocket bored
#: into solid material and bottoming out inside it, which is exactly what a
#: large tapped bore looks like. machined_block's 25 mm blind bore, 18 mm deep
#: (0.72 x diameter of engagement) in a 30 mm block, is a credible M27 x 2.
#: The cap is therefore applied only to through holes.
_MAX_TAPPED_DIA_THROUGH = 20.0

#: Minimum depth as a multiple of diameter for a thread to hold. Below roughly
#: this there are too few engaged turns, so the hole is a clearance or pilot
#: hole. Applies to blind and through holes alike -- a 9 mm hole through 6 mm
#: of plate has two thirds of a diameter of engagement.
_MIN_ENGAGEMENT = 0.5

#: Tolerance magnitudes, R10 preferred numbers in mm. Real frames use round
#: values like these, not arbitrary decimals.
TOL_VALUES = (0.05, 0.08, 0.1, 0.12, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.8)

#: Chamfer angles a real print calls out, as the HALF angle measured from the
#: hole axis -- i.e. the number printed in "1 X 45 deg". Chamfer.angle stores
#: the INCLUDED angle (twice this), because that is what a recognised cone
#: reports and what a countersink is called out by, so these are doubled on
#: construction. Getting that wrong printed "0.7 X 15 deg" for a 30 deg
#: chamfer.
CHAMFER_HALF_ANGLES = (45.0, 30.0, 60.0)

#: Characteristics that make sense on a planar face of a plate, and the
#: datum-reference arity each one takes. Form tolerances (flatness,
#: straightness) reference no datum -- citing one would be a drafting error.
_FACE_CHARACTERISTICS = (
    ("flatness", 0),
    ("parallelism", 1),
    ("perpendicularity", 1),
    ("profile_surface", 3),
)

#: Characteristics that make sense on a cylindrical bore.
_BORE_CHARACTERISTICS = (
    ("position", 3),
    ("perpendicularity", 1),
    ("cylindricity", 0),
    ("concentricity", 1),
)


def _seed(text: str) -> int:
    """Stable integer from a name. BLAKE2b: hash() is salted per process."""
    return int.from_bytes(
        hashlib.blake2b(text.encode("utf-8"), digest_size=8).digest(), "big")


class _Picker:
    """Deterministic sequence of choices from one seed.

    A plain modulo of the same seed for every decision correlates them (all
    parts whose hash is even get the same everything), so the seed is advanced
    with a cheap LCG between draws.
    """

    def __init__(self, seed: int):
        self._s = seed or 1

    def _next(self) -> int:
        # Numerical Recipes LCG constants; adequate for choosing from lists.
        self._s = (self._s * 6364136223846793005 + 1442695040888963407) \
            % (1 << 64)
        return self._s >> 16

    def pick(self, seq):
        return seq[self._next() % len(seq)]

    def chance(self, num: int, den: int) -> bool:
        return (self._next() % den) < num


def _nearest_thread(bore_dia: float) -> Optional[Tuple[float, float]]:
    """Map a bore to the metric thread it could be tapped for.

    A tapped hole is drilled at nominal - pitch, so an M6 x 1.0 tapped hole is
    a 5.0 mm bore. The match must be tight: a 5.5 mm bore is not an M6 tap
    drill and calling it one would be wrong on the shop floor.

    Both the coarse and fine ISO 965 series are searched. Where a bore fits
    both -- an 8.0 mm bore is neither, but a 10.25 mm bore is M12 coarse while
    10.0 mm is M12 x 1.5 fine -- the closest match wins, and coarse breaks an
    exact tie because that is what a drawing means when it does not say
    otherwise.

    Returns ``(nominal, pitch)`` or None when no standard thread fits.
    """
    best = None
    for tap_drill, nominal, pitch, coarse in _thread_candidates():
        # +/-4% of the tap drill covers the real spread of drill sizes used
        # (e.g. M6 coarse is tapped 5.0 mm, sometimes 5.1 mm).
        err = abs(bore_dia - tap_drill)
        if err > max(tap_drill * 0.04, 0.05):
            continue
        # sort key: closest first, then coarse before fine, then the smaller
        # pitch, so the choice is deterministic rather than dict-order.
        key = (round(err, 6), 0 if coarse else 1, pitch)
        if best is None or key < best[0]:
            best = (key, nominal, pitch)
    return (best[1], best[2]) if best else None


def _datum_letters(n: int) -> Tuple[str, ...]:
    """The first n datum letters. I, O and Q are skipped per ASME Y14.5."""
    return tuple("ABCDEFGHJKLMNPRSTUVWXYZ"[:n])


def _face_anchor_point(info):
    """A point on the part's largest flat face, in model coordinates.

    Used to anchor a face tolerance. The centre of the bounding box, pushed
    out to the top face, is on real material for the plate-like parts this is
    applied to; the annotator then snaps the leader to the nearest drawn edge,
    so a small inaccuracy here cannot leave an arrow in mid-air.
    """
    b = info.bbox
    return ((b.xmin + b.xmax) / 2.0, (b.ymin + b.ymax) / 2.0, b.zmax)


#: A part whose longest edge is below this is treated as unitless/normalised
#: geometry rather than a real sub-millimetre object. See _match_scale.
_TINY_PART_MM = 10.0

#: The size a normalised part is assumed to represent, as the longest edge in
#: millimetres. 120 mm is a typical machined bracket or plate -- large enough
#: that its features land on ordinary fastener sizes, small enough to stay a
#: single-setup part.
_ASSUMED_PART_MM = 120.0


#: A through hole spanning more than this fraction of the part's longest edge
#: is an aperture, whatever its absolute size.
_APERTURE_FRAC = 0.35


def _longest_mm(info, scale: float) -> float:
    """Longest bounding-box edge, multiplied by `scale`."""
    b = getattr(info, "bbox", None)
    if b is None:
        return float("inf")
    return max(b.xlen, b.ylen, b.zlen) * scale


def _match_scale(info) -> float:
    """Factor mapping model units to the millimetres used for THREAD MATCHING.

    Most of this corpus is not really sub-millimetre hardware: the files
    declare ``SI_UNIT(.MILLI.,.METRE.)`` with no scaling transform, yet 16 of
    24 sample parts have a longest edge under 1.5 mm and bores as small as
    0.047 mm. A 47-micron hole is not a manufacturable feature; the geometry
    is normalised, exported as though the units were millimetres.

    Thread standards are absolute -- the smallest real metric thread, M1,
    needs a 0.75 mm tap drill -- so matching such a part's bores against them
    finds nothing, which is why ``threads`` stayed at ~1% of ``bores``.
    Normalised geometry is therefore scaled to a plausible physical size
    before the thread lookup runs.

    **This scale affects thread selection only.** Every dimension the drawing
    prints, and every value in the records, stays in the model's own units --
    a 0.34 mm bore is still dimensioned 0.34. The thread designation is the
    one thing that cannot be expressed at normalised scale, because "M0.0004"
    does not exist.

    Returns 1.0 for parts that are already a believable physical size, so
    normal CAD is never rescaled.
    """
    b = getattr(info, "bbox", None)
    if b is None:
        return 1.0
    longest = max(b.xlen, b.ylen, b.zlen)
    if longest <= 0 or longest >= _TINY_PART_MM:
        return 1.0
    return _ASSUMED_PART_MM / longest


def generate(part_name: str, info, existing: PMI) -> PMI:
    """Add synthetic PMI to ``existing``, in place, and return it.

    A file that already carries real PMI is left alone: the NIST part has 34
    genuine feature control frames and a real thread, and burying those under
    invented ones would corrupt the only ground truth in the corpus.
    """
    if existing.tolerances or existing.threads:
        return existing

    pick = _Picker(_seed(part_name))
    bores = [h for h in getattr(info, "holes", []) if getattr(h, "is_closed", True)]

    # ---- datums --------------------------------------------------------- #
    # Every datum letter a frame cites must be defined by a datum feature
    # symbol on the drawing, so the letters are allocated first and the frames
    # below only ever reference from this set.
    n_datums = 3 if bores else 2
    letters = _datum_letters(n_datums)
    existing.datums = [DatumFeature(letter=ch, synthetic=True)
                       for ch in letters]

    tols: List[GeomTolerance] = []

    # ---- face tolerances ------------------------------------------------- #
    # A plate has large flat faces, which is exactly what a form or
    # orientation tolerance applies to.
    if getattr(info, "is_plate", False):
        char, arity = pick.pick(_FACE_CHARACTERISTICS)
        # A form tolerance takes no datum; an orientation tolerance must not
        # reference the very face it controls, so it cites the primary datum.
        refs = letters[:arity]
        tols.append(GeomTolerance(
            characteristic=char, value=pick.pick(TOL_VALUES),
            datums=refs, diametral=False,
            anchor=_face_anchor_point(info), synthetic=True))

    # ---- bore tolerances -------------------------------------------------- #
    # Position is the commonest characteristic on a real print and always
    # applies to a feature of size, so it goes on a bore. A positional zone is
    # diametral -- the zone is a cylinder around the true position.
    for h in bores[:2]:
        char, arity = pick.pick(_BORE_CHARACTERISTICS)
        # A diameter symbol means the zone is cylindrical, which applies to
        # controls on an AXIS (position, concentricity). Cylindricity is a
        # FORM control on the surface itself and never takes one -- "o0.8
        # cylindricity" is a drafting error.
        diametral = char in ("position", "concentricity")
        val = pick.pick(TOL_VALUES)
        # A positional tolerance looser than the hole itself is meaningless;
        # keep the zone a sensible fraction of the feature it locates.
        val = min(val, round(h.diameter * 0.15, 2)) or 0.05
        mod = None
        if char == "position" and pick.chance(1, 2):
            # MMC is the usual modifier on a positional callout for a clearance
            # hole; it is never applied to a form tolerance.
            mod = "M"
        tols.append(GeomTolerance(
            characteristic=char, value=val,
            datums=letters[:arity] if char != "cylindricity" else (),
            diametral=diametral, modifier=mod,
            anchor=(h.x, h.y, h.z), synthetic=True))

    existing.tolerances = tols

    # ---- threads ---------------------------------------------------------- #
    # Only on a bore whose diameter really is a standard tap drill. This is
    # the one place the geometry constrains the specification completely: the
    # bore size determines the thread, so nothing is free to be invented.
    threads: List[Thread] = []
    by_dia = {}
    # Normalised geometry is matched at its assumed physical size; real CAD
    # gets 1.0 and is untouched. Only the LOOKUP is scaled -- printed
    # dimensions stay in the model's own units. See _match_scale.
    ms = _match_scale(info)
    for h in bores:
        # A counterbored or countersunk hole is a CLEARANCE hole -- the recess
        # takes the head of a screw that passes through and threads into
        # something else. It is never itself tapped, so threading one would be
        # a real drafting error, not merely a synthetic value. This excludes
        # machined_block's and bracket's 6.6 mm counterbored holes, which are
        # M6 clearance, and the flange's countersunk 9 mm holes.
        if h.counterbore is not None or h.countersink is not None:
            continue
        # A large bore that passes clean THROUGH is the part's main aperture,
        # not a tapped hole -- flange's 45 mm centre and bracket_plate's 40 mm
        # cutout would otherwise read as M48 and M45. A large BLIND bore is a
        # pocket bored into solid material and is credibly tapped, so the cap
        # applies only to through holes. See _MAX_TAPPED_DIA_THROUGH.
        # A large through bore is the part's main aperture. "Large" is judged
        # two ways, because neither alone is right:
        #
        #  * absolutely -- above ~20 mm a through hole is an opening, not a
        #    fastener hole (flange's 45 mm centre);
        #  * relatively -- a hole spanning half its part is an aperture at any
        #    size, while a 30 mm hole in a 300 mm plate is an ordinary bolt
        #    hole. Judging only absolutely rejected 0000_00000093's four-hole
        #    pattern, each 25% of the part, which is a perfectly normal bolt
        #    circle, while accepting a single hole covering 72% of another.
        if h.through:
            # EITHER bound is disqualifying, so these are separate tests. They
            # were briefly combined with `and`, which meant a bore had to fail
            # both -- and a part with no bounding box makes the relative test
            # infinite, so nothing was ever rejected.
            if h.diameter * ms > _MAX_TAPPED_DIA_THROUGH:
                continue
            if h.diameter > _longest_mm(info, 1.0) * _APERTURE_FRAC:
                continue
        # A thread needs material to engage with. Less than ~0.5 x diameter of
        # depth gives too few turns to hold, so a shallow hole in thin sheet
        # is a clearance or pilot hole, not a tapped one. This is a RATIO, so
        # it is scale-free and needs no conversion.
        if h.depth < h.diameter * _MIN_ENGAGEMENT:
            continue
        m = _nearest_thread(h.diameter * ms)
        if m is None:
            continue
        by_dia.setdefault(m, []).append(h)
    # Every distinct thread size on the part gets its own callout. This was
    # capped at 2, which silently dropped real sizes on a part with three or
    # more; Style.thread_max_notes already limits how many are DRAWN on a
    # view, so capping here as well just hid data from the record.
    for (nominal, pitch), group in sorted(by_dia.items()):
        cls = pick.pick(THREAD_CLASSES)
        threads.append(Thread(
            designation=f"M{nominal:g} x {pitch:g}-{cls}",
            count=len(group), nominal=nominal,
            anchor=(group[0].x, group[0].y, group[0].z),
            axis=tuple(group[0].axis), synthetic=True))
    existing.threads = threads

    return existing


def generate_chamfers(part_name: str, info) -> List[Chamfer]:
    """Chamfers on real bore mouths, for parts with no recognised conical face.

    A drilled or bored hole in a machined part is normally broken at the mouth
    -- it is one of the commonest callouts on a real drawing, and the sample
    parts simply were not modelled with the feature. The break is sized from
    the bore it belongs to, so a 3 mm hole gets a 0.3 mm break and a 20 mm
    hole gets a 1.5 mm one, rather than a fixed size that would look absurd on
    one of them.

    Returns [] when the part already has recognised chamfers, so the flange's
    six genuine 82 deg countersinks are never displaced by invented ones.
    """
    if getattr(info, "chamfers", None):
        return []
    # A counterbored or countersunk hole already HAS a machined mouth -- the
    # recess is the entry feature. Calling out an extra edge break on it is a
    # drafting error and double-dimensions the same edge, so those holes are
    # excluded exactly as they are for threads.
    bores = [h for h in getattr(info, "holes", [])
             if getattr(h, "is_closed", True)
             and h.counterbore is None and h.countersink is None]
    if not bores:
        return []

    pick = _Picker(_seed(part_name + ":chamfer"))
    half = pick.pick(CHAMFER_HALF_ANGLES)

    # Group identical bores so a pattern of six reads as "6X", exactly as a
    # recognised chamfer would.
    groups = {}
    for h in bores:
        groups.setdefault(round(h.diameter, 3), []).append(h)

    out: List[Chamfer] = []
    for dia, group in sorted(groups.items(), key=lambda kv: -len(kv[1]))[:1]:
        # Standard edge break: ~10% of diameter, clamped to sizes a machinist
        # would actually cut, and rounded to a tenth of a millimetre.
        width = max(0.2, min(1.5, round(dia * 0.1, 1)))
        h = group[0]
        out.append(Chamfer(
            angle=half * 2.0, width=width,
            radius_max=dia / 2 + width, radius_min=dia / 2,
            count=len(group), countersink=False,
            position=(h.x, h.y, h.z), axis=h.axis, synthetic=True))
    return out
